/**
 * 通常将表格的控制器URL定义在此处
 * 然后就可以使用/@/api/common中的baTableApi类生成各个操作的url以供table进行增删改查
 */
export const authMenu = '/index.php/admin/auth.menu/'
export const authAdmin = '/index.php/admin/auth.admin/'
export const authAdminLog = '/index.php/admin/auth.adminLog/'
export const authGroup = '/index.php/admin/auth.group/'
export const routineAttachment = '/index.php/admin/routine.attachment/'
export const userUser = '/index.php/admin/user.user/'
export const userGroup = '/index.php/admin/user.group/'
export const userRule = '/index.php/admin/user.rule/'
export const userScoreLog = '/index.php/admin/user.scoreLog/'
export const userMoneyLog = '/index.php/admin/user.moneyLog/'
export const securityDataRecycle = '/index.php/admin/security.dataRecycle/'
export const securityDataRecycleLog = '/index.php/admin/security.dataRecycleLog/'
export const securitySensitiveData = '/index.php/admin/security.sensitiveData/'
export const securitySensitiveDataLog = '/index.php/admin/security.sensitiveDataLog/'
export const adPositions = '/index.php/admin/ad.positions/'
export const adAds = '/index.php/admin/ad.ads/'
export const linkLinks = '/index.php/admin/link.links/'
export const linksIndex = '/index.php/admin/links.index/'
export const seosIndex = '/index.php/admin/seos.index/'
export const articleMenus = '/index.php/admin/article.menus/'
export const articleArticles = '/index.php/admin/article.articles/'
export const articleComments = '/index.php/admin/article.comments/'
export const articleStatics = '/index.php/admin/article.statics/'
export const articleContacts = '/index.php/admin/article.contacts/'
export const mallMenus = '/index.php/admin/mall.menus/'
export const mallGoods = '/index.php/admin/mall.goods/'
export const mallOrder = '/index.php/admin/mall.order/'
export const order = '/index.php/admin/order/'
